language: python
python:
  - "3.6"
env:
  - NIKOLA_DEPLOY=python.ec
install:
  - pip install -r requirements.txt
script:
  - nox

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  keep_history: true
  target_branch: master
  on:
    branch: src
